In [13]:
import pandas as pd
df = pd.read_csv("uae_real_estate_2024.csv")

In [14]:
print(df.head())
print(df.info())
print(df.description)

                                              title  \
0               Great ROI I High Floor I Creek View
1  Full Sea View | Beach Life | Brand New Residence
2          Green Belt | Corner Unit | Spacious Plot
3          2BR+Study | Near Pool and Park | Private
4            Vacant | Well Maintained | Area Expert

                            displayAddress bathrooms bedrooms  \
0     Binghatti Canal, Business Bay, Dubai         3        2
1  La Vie, Jumeirah Beach Residence, Dubai         3        2
2  La Rosa 6, Villanova, Dubai Land, Dubai         3        4
3           Springs 15, The Springs, Dubai         3        2
4      Noor Townhouses, Town Square, Dubai         3        3

                addedOn                  type    price  verified  \
0  2024-08-14T12:02:53Z  Residential for Sale  2500000      True
1  2024-08-13T05:45:16Z  Residential for Sale  7200000      True
2  2024-08-14T06:24:28Z  Residential for Sale  3600000      True
3  2024-08-15T06:07:22Z  Residential for Sale  2999999      True
4  2024-08-09T08:28:59Z  Residential for Sale  2449999      True

  priceDuration    sizeMin furnishing  \
0          sell  1323 sqft         NO
1          sell  1410 sqft        YES
2          sell  2324 sqft         NO
3          sell  1647 sqft         NO
4          sell  2105 sqft         NO

                                         description
0  MNA Properties is delighted to offer this apar...
1  Apartment for sale in La Vie, Jumeirah Beach R...
2  Treo Homes is very pleased to be bringing to t...
3  2 Bedrooms + Study | Near Pool &amp; Park | Pr...
4  -Type 1\n-3 Bed+Maid\n-Close To Amenities\n-BU...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5058 entries, 0 to 5057
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           5058 non-null   object
 1   displayAddress  5058 non-null   object
 2   bathrooms       4938 non-null   object
 3   bedrooms        4935 non-null   object
 4   addedOn         5058 non-null   object
 5   type            5058 non-null   object
 6   price           5058 non-null   int64
 7   verified        5058 non-null   bool
 8   priceDuration   5058 non-null   object
 9   sizeMin         5058 non-null   object
 10  furnishing      5056 non-null   object
 11  description     5057 non-null   object
dtypes: bool(1), int64(1), object(10)
memory usage: 439.7+ KB
None
0       MNA Properties is delighted to offer this apar...
1       Apartment for sale in La Vie, Jumeirah Beach R...
2       Treo Homes is very pleased to be bringing to t...
3       2 Bedrooms + Study | Near Pool &amp; Park | Pr...
4       -Type 1\n-3 Bed+Maid\n-Close To Amenities\n-BU...
                              ...
5053    Nobel Victory Real Estate are proud to present...
5054    Discover Address Residence by Emaar, nestled o...
5055    Rocky Real Estate presents an Exclusive and up...
5056    Dingstone Real Estate is pleased to present to...
5057    Introducing Avena, the valleyâ€™s newest and mos...
Name: description, Length: 5058, dtype: object

In [16]:
df.dropna(subset=['price','bedrooms','bathrooms'])

,title,displayAddress,bathrooms,bedrooms,addedOn,type,price,verified,priceDuration,sizeMin,furnishing,description
0,Great ROI I High Floor I Creek View,"Binghatti Canal, Business Bay, Dubai",3,2,2024-08-14T12:02:53Z,Residential for Sale,2500000,True,sell,1323 sqft,NO,MNA Properties is delighted to offer this apar...
1,Full Sea View | Beach Life | Brand New Residence,"La Vie, Jumeirah Beach Residence, Dubai",3,2,2024-08-13T05:45:16Z,Residential for Sale,7200000,True,sell,1410 sqft,YES,"Apartment for sale in La Vie, Jumeirah Beach R..."
2,Green Belt | Corner Unit | Spacious Plot,"La Rosa 6, Villanova, Dubai Land, Dubai",3,4,2024-08-14T06:24:28Z,Residential for Sale,3600000,True,sell,2324 sqft,NO,Treo Homes is very pleased to be bringing to t...
3,2BR+Study | Near Pool and Park | Private,"Springs 15, The Springs, Dubai",3,2,2024-08-15T06:07:22Z,Residential for Sale,2999999,True,sell,1647 sqft,NO,2 Bedrooms + Study | Near Pool &amp; Park | Pr...
4,Vacant | Well Maintained | Area Expert,"Noor Townhouses, Town Square, Dubai",3,3,2024-08-09T08:28:59Z,Residential for Sale,2449999,True,sell,2105 sqft,NO,-Type 1\n-3 Bed+Maid\n-Close To Amenities\n-BU...
...,...,...,...,...,...,...,...,...,...,...,...,...
5053,07 Layout | Handover Q2 2025 | Multiple Units ...,"Sobha Creek Vistas Grande, Sobha Hartland, Moh...",3,2,2024-07-10T14:07:57Z,Residential for Sale,2345000,True,sell,1268 sqft,PARTLY,Nobel Victory Real Estate are proud to present...
5054,Emaar | Waterfront Apartment | 10% DP | 5-Yr PP,"Al Marjan Island, Ras Al Khaimah",2,1,2024-08-12T13:08:33Z,Residential for Sale,3007888,False,sell,854 sqft,NO,"Discover Address Residence by Emaar, nestled o..."
5055,Upgraded | Spacious With Private Garden,"Oia Residence, Motor City, Dubai",5,4,2024-04-20T08:43:16Z,Residential for Sale,4000000,True,sell,3813 sqft,NO,Rocky Real Estate presents an Exclusive and up...
5056,"10 Series | Full Sea, Burj Khalifa View Exclusive","The Grand, Dubai Creek Harbour (The Lagoons), ...",2,2,2024-07-08T07:05:56Z,Residential for Sale,3800000,True,sell,1300 sqft,NO,Dingstone Real Estate is pleased to present to...
5057,Family Home | Unique Design | Attracrive Price,"Avena, The Valley, Dubai",5,4,2024-07-16T06:57:49Z,Residential for Sale,4360000,False,sell,3685 sqft,NO,"Introducing Avena, the valleyâ€™s newest and mos..."

In [17]:
avg_price_by_type = df.groupby('type')['price'].mean()
print(avg_price_by_type)

type
Residential for Sale    5.050924e+06
Name: price, dtype: float64

In [19]:
verified_count = df['verified'].value_counts()
print(verified_count)

verified
True     3271
False    1787
Name: count, dtype: int64

In [20]:
df.to_csv("cleaned_uae_real_estate_2024.csv", index=False)